#!/bin/sh
ssh -t -t ubuntu@172.31.2.177 <<EOF
 cd ~/deploy
 git clone https://github.com/mohanemmadi/node.git
 sudo apt install npm -y
 sudo apt-get update
 sudo npm install -g pm2
 pm2 restart all 
exit
EOF
 
